@baseUrl = http://localhost:3000
@acessToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Claudio Medeiros",
    "email": "claudiomedeiros123@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "claudiomedeiros@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{acessToken}}

{
    "title": "Nova pergunta",
    "content": "Conteúdo da pergunta.."
}

###

# @name fetch_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{acessToken}}