version: '3'

volumes:
  db-data:

services:
  nestjs-clean-pg:
    container_name: nestjs-clean-pg
    image: bitnami/postgresql
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nestjs_clean